#!/bin/bash
## This script creates users and groups with the given name and ID.
## The name of user and group is same as the same group will be used to create the user
## If the user and group is already there, it changes its Id to the one listed
## The script is for linux, duh!!!

## Use case: in case a number of systems share a single resource (file share) and the resource may have permissions based on user id
## and there is no central access managmeent like Azure AD or other

## declare an array variable 
declare -a usrngpname=("user1" "user2" "user3")
declare -a usrngpid=(997 1001 33)

# get length of an array
length=${#usrngpname[@]}

myrandom=$(date '+%Y-%m-%d-%H-%M-%S')
mkdir -p /extensionlogs
touch "/extensionlogs/customscript-${myrandom}.log"

printf "Starting at $(date)" >> "/extensionlogs/customscript-${myrandom}.log"
printf "\n" >> "/extensionlogs/customscript-${myrandom}.log"
printf "current working directory: $(pwd)" >> "/extensionlogs/customscript-${myrandom}.log"
printf "\n" >> "/extensionlogs/customscript-${myrandom}.log"

# use C style for loop syntax to read all values and indexes
for (( j=0; j<length; j++ ));
do
    printf "=======================================================" >> "/extensionlogs/customscript-${myrandom}.log"
    printf "Current index %d with value %s\n" $j "${usrngpname[$j]}" >> "/extensionlogs/customscript-${myrandom}.log"
    printf "\n" >> "/extensionlogs/customscript-${myrandom}.log"
    printf "Current index %d with value %s\n" $j "${usrngpid[$j]}" >> "/extensionlogs/customscript-${myrandom}.log"
    printf "\n" >> "/extensionlogs/customscript-${myrandom}.log"

    if id -u "${usrngpname[$j]}" >/dev/null 2>&1; then
        printf "user exists" >> "/extensionlogs/customscript-${myrandom}.log"
        printf "\n" >> "/extensionlogs/customscript-${myrandom}.log"

        groupmod -g "${usrngpid[$j]}" "${usrngpname[$j]}" >> "/extensionlogs/customscript-${myrandom}.log"
        printf "\n" >> "/extensionlogs/customscript-${myrandom}.log"
        usermod -u "${usrngpid[$j]}" -g "${usrngpname[$j]}" "${usrngpname[$j]}" >> "/extensionlogs/customscript-${myrandom}.log"
        printf "\n" >> "/extensionlogs/customscript-${myrandom}.log"
        id "${usrngpname[$j]}" >> "/extensionlogs/customscript-${myrandom}.log"
        printf "\n" >> "/extensionlogs/customscript-${myrandom}.log"
    else
        printf "user does not exist" >> "/extensionlogs/customscript-${myrandom}.log"
        printf "\n" >> "/extensionlogs/customscript-${myrandom}.log"
        groupadd -g "${usrngpid[$j]}" "${usrngpname[$j]}" >> "/extensionlogs/customscript-${myrandom}.log"
        printf "\n" >> "/extensionlogs/customscript-${myrandom}.log"
        useradd -m  -u "${usrngpid[$j]}"  -g "${usrngpname[$j]}" "${usrngpname[$j]}" >> "/extensionlogs/customscript-${myrandom}.log" 
        printf "\n" >> "/extensionlogs/customscript-${myrandom}.log"
        id "${usrngpname[$j]}" >> "/extensionlogs/customscript-${myrandom}.log"
        printf "\n" >> "/extensionlogs/customscript-${myrandom}.log"
    fi
done
