#!/bin/bash
## This script creates users and groups with the given name and ID.
## The name of user and group is same as the same group will be used to create the user
## If the user and group is already there, it changes its Id to the one listed
## The script is for linux, duh!!!

## Use case: in case a number of systems share a single resource (file share) and the resource may have permissions based on user id
## and there is no central access managmeent like Azure AD or other

## declare an array variable 
declare -a usrngpname=("user1" "user2" "user3")
declare -a usrngpid=(997 1001 33)

# get length of an array
length=${#usrngpname[@]}

# use C style for loop syntax to read all values and indexes
for (( j=0; j<length; j++ ));
do
    printf "Current index %d with value %s\n" $j "${usrngpname[$j]}"
    printf "Current index %d with value %s\n" $j "${usrngpid[$j]}"

    if id -u "${usrngpname[$j]}" >/dev/null 2>&1; then
        echo "user exists"
        groupmod -g "${usrngpid[$j]}" "${usrngpname[$j]}"
        usermod -u "${usrngpid[$j]}" -g "${usrngpname[$j]}" "${usrngpname[$j]}"
        id "${usrngpname[$j]}"
    else
        echo "user does not exist"
        groupadd -g "${usrngpid[$j]}" "${usrngpname[$j]}"
        useradd -m  -u "${usrngpid[$j]}"  -g "${usrngpname[$j]}" "${usrngpname[$j]}"
        id "${usrngpname[$j]}"
    fi
done
